version: 0.1

environment_variables:
  plaintext:
    key: "value"
    key2: "value2"

phases:
  install:
    commands:
      - apt-get install zip
  pre_build:
    commands:
      - pip install jinja2 -t blogless/
      - pip install setuptools -t blogless/
  build:
    commands:
      - ls
  post_build:
    commands:
      - cd blogless
      - zip blogless.zip *
      - cd ..
artifacts:
  files:
    - blogless/blogless.zip
  discard-paths: yes
